
server.port=8383

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3307/spring
spring.datasource.username=root
spring.datasource.password=mariadb